### ISSUE TITLE
Parametric number special characters

### ISSUE THREAD

**Issue by n-yavuz** [foex-open-source/fos-advanced-password#2]
I'm trying to make password strength parametric so that I can change the required number of digits and required number of special characters with page item substitutions. It works for required number of digits but I cannot make the number of special characters parametric. What I want to do is that when I the page item substitution value that defined the required number of special characters is null then I also don't want to see the list of special characters. So basically is there a workaround to make the plugin behave like “Required Special Character(s)” section is never selected depending on that page item value?

**Comment by foex-open-source** [comment]
The feature has been added with 21.2.
